### ISSUE TITLE
Some classic Taito fixes

### ISSUE THREAD

**Issue by arcadez2003** [arcadez2003/Classic-Cades#1]
@mahoneyt944 @grant2258 @KMFDManic

You might be interested in a couple of fixes i've done for Operation Wolf and The Legend Of Kage for your own projects
i'll quickly explain what the fixes are for each game.

Operation Wolf

After a more in depth playtest it's clear the c-chip simulation which was updated in MAME176 using data from the
the location test version of this game is clearly faulty and broken, most of the gameplay features dont trigger correctly
half of the time and there are two which will cause game breaking bugs this is the code we use in MAME2003+ etc etc

End of Level 2 Boss

If you die on the boss which isn't uncommon due to the games difficulty when you respawn after continuing the level
will be be totally borked in the game logic dept you cannnot complete it in that state and a soft reset will then be required
rinse and repeat.

End of Game Boss Sequence

At the end of the game you have to shoot 10 helicopters and then a souped up helicopter with missles which is the end
boss, on a ratio of 75% the following will happen due to the flawed c-chip sim, the helicopters will be borked in the sense
they're displayed and positioned incorrectly on screen and cant be shotdown which again will render the game unplayable
you wont be able to complete the level so will have to reset and start the game all over again.

Luckly the older c-chip simulation from MAME98 is more solid there are no problems with the end boss and taking ideas
from this unlicenced txt file https://github.com/mamedev/mame/blob/master/src/mame/etc/opwolf_cchip.txt
I've updated the level data tables and enabled the c-chip trigger for the random enemy has located you mini levels.

Basically in a nutshell i've got rid of the unreliable newer gamebreaking c-chip sim and replaced it with the better and 
more stable earlier one plus as a bonus we get to keep two of the best gameplay features which would have been 
missing in MAME78 eg the end boss and the random mini levels.

i've fully tested this end to end including purposely dying over and over on the end game and the bonus levels to 
make sure the respwans are correct and i've bumped into no issues with the gameplay.

The Legend Of Kage

I've updated the driver and video to MAME100 this sorts some graphical niggles in the game eg visable area is now
correct you dont have those black borders on each side of the playfield, and the graphical prios are now correct
most noticeable on the title screen and level 4, finally i've fixed two of the bootlegs which were not using the
correct mcu code previously so they now work.

There ya go some good fixes for a couple of classic Taito games i highly recommend you implement them in your
own projects check my latest commits here for the code but at the end of the day the choice is surely yours :)

Regards

**Comment by grant2258** [comment]
I haven't touched my fork in ages to be honest. Last thing I done was an a mostly complete update to the ay soundchip its nice to see your still about thought m8.

**Comment by mahoneyt944** [comment]
I can verify if you want, but I'm fairly certain you're allowed to create PRs for 2003+ which I'm allowed to merge. If you don't want to I can certainly push these there.

**Comment by arcadez2003** [comment]
> I haven't touched my fork in ages to be honest. Last thing I done was an a mostly complete update to the ay soundchip its nice to see your still about thought m8.

Ah right i thought i minded you sayin you had built a mini barcade and your blaster barcade core is what you use
in it hence why i tagged ya as i thought you might want these fixes, but no worries and as always good to talk with ya.

**Comment by arcadez2003** [comment]
> I can verify if you want, but I'm fairly certain you're allowed to create PRs for 2003+ which I'm allowed to merge. If you don't want to I can certainly push these there.

It's better i lie low for now, as for the commits feel free to add em whenever you have the time there are some good
solid fixes in there, plus as we discussed when it comes to opwolf.c that txt file being used as the source will save 
some hastles down the road ;)

As always thanks for helping me out.

**Comment by mahoneyt944** [comment]
You should rebase and update the changelog as well. 😉

**Comment by grant2258** [comment]
@arcadez2003 I used to use it on the pi use a mini pc now with latest mame for that have done that for a good while now. I dont even use plus or even my own core. My own is in a state that if my mini pc breaks I can use it. I havent back ported much to it probably would add some of the stuff if i had to use the pi though.

**Comment by arcadez2003** [comment]
> You should rebase and update the changelog as well. 😉

Aye there are a fair few conflicts to work through it'll be easier to just delete this and refork :)
